package com.enaboapps.switchify.nav

sealed class NavigationRoute(val name: String) {

    data object Home : NavigationRoute("Home")
    data object Onboarding : NavigationRoute("Onboarding")
    data object Paywall : NavigationRoute("Paywall")
    data object Authentication : NavigationRoute("Authentication")
    data object Account : NavigationRoute("Account")
    data object Settings : NavigationRoute("Settings")
    data object SwitchHold : NavigationRoute("SwitchHold")
    data object SwitchStability : NavigationRoute("SwitchStability")
    data object AdvancedGestureSettings : NavigationRoute("AdvancedGestureSettings")
    data object ScrollingSettings : NavigationRoute("ScrollingSettings")
    data object ScanSpeeds : NavigationRoute("ScanSpeeds")
    data object ManualScanSettings : NavigationRoute("ManualScanSettings")
    data object ScanColor : NavigationRoute("ScanColor")
    data object AutoScanSettings : NavigationRoute("AutoScanSettings")
    data object AccessTechniqueSettings : NavigationRoute("AccessTechniqueSettings")
    data object Switches : NavigationRoute("Switches")
    data object SwitchProfiles : NavigationRoute("SwitchProfiles")
    data object SwitchProfileDetail : NavigationRoute("SwitchProfileDetail")
    data object ExternalSwitches : NavigationRoute("ExternalSwitches")
    data object CameraSwitches : NavigationRoute("CameraSwitches")
    data object AddNewExternalSwitch : NavigationRoute("AddNewExternalSwitch")
    data object EditExternalSwitch : NavigationRoute("EditExternalSwitch")
    data object EnableAccessibilityService : NavigationRoute("EnableAccessibilityService")
    data object AddNewCameraSwitch : NavigationRoute("AddNewCameraSwitch")
    data object EditCameraSwitch : NavigationRoute("EditCameraSwitch")
    data object Debug : NavigationRoute("Debug")
    data object GesturePatterns : NavigationRoute("GesturePatterns")

    data object UserFeedback : NavigationRoute("UserFeedback")
    data object Stats : NavigationRoute("Stats")
    data object CameraSettings : NavigationRoute("CameraSettings")
    data object PauseSettings : NavigationRoute("PauseSettings")
    data object MenuCustomization : NavigationRoute("MenuCustomization")
    data object MenuCustomizationEdit : NavigationRoute("MenuCustomizationEdit")
    data object SwitchActionSelection : NavigationRoute("SwitchActionSelection")
    data object LongPressActions : NavigationRoute("LongPressActions")
    data object FavouriteApps : NavigationRoute("FavouriteApps")
    data object AiModel : NavigationRoute("AiModel")
    data object GemmaTerms : NavigationRoute("GemmaTerms")
}
